# Generated by Django 6.0.7 on 2026-07-22 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        ('vendors', '0002_rename_shares_per_unit_menuitem_portions_per_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('locked', 'Locked'), ('submitted', 'Submitted'), ('completed', 'Completed')], default='open', max_length=20)),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organisations.organisation')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='vendors.vendor')),
            ],
        ),
    ]
