# Generated by Django 6.0.7 on 2026-09-11 15:04

from django.db import migrations, models


def merge_completed_into_submitted(apps, schema_editor):
    # 'completed' is being dropped as a distinct stage - it and the old
    # 'submitted' both meant "finalized" already, so any existing
    # 'completed' events become 'submitted', the new (and now only) final
    # status, rather than being left holding a value that's no longer a
    # valid choice.
    Event = apps.get_model('events', 'Event')
    Event.objects.filter(status='completed').update(status='submitted')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_public_id'),
    ]

    operations = [
        migrations.RunPython(merge_completed_into_submitted, noop_reverse),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('locked', 'Locked'), ('open', 'Open'), ('closed', 'Closed'), ('submitted', 'Submitted')], default='locked', max_length=20),
        ),
    ]
