"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from decouple import config, Csv

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=Csv())

# Needed once real HTTPS traffic reaches this app through a reverse proxy -
# Django's CSRF check compares the request's Origin/Referer against this list
# rather than ALLOWED_HOSTS. e.g. CSRF_TRUSTED_ORIGINS=https://pizzapool.example.com
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())

# Security settings for deployment, overridable via env vars.
#
# SESSION_COOKIE_SECURE/CSRF_COOKIE_SECURE just add the `Secure` flag to
# cookies, so they're safe to default on whenever DEBUG is off.
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=not DEBUG, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=not DEBUG, cast=bool)

# SECURE_SSL_REDIRECT, unlike the cookie flags above, actively 301-redirects
# every non-HTTPS request, including in-process requests like the Django
# test client's and any CI run with DEBUG=False, which aren't going through
# real TLS termination. It only makes sense once a reverse proxy is actually
# terminating HTTPS in front of this app, so it stays opt-in (default False)
# rather than tied to DEBUG, and its deploy check is silenced alongside HSTS
# below until that's true.
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)

# Inert until a reverse proxy actually sends this header. Whichever proxy is
# used in front of this app MUST strip/overwrite any client-supplied
# X-Forwarded-Proto before it reaches Django, or this becomes spoofable.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# security.W008 (SECURE_SSL_REDIRECT) and W004 (SECURE_HSTS_SECONDS) are
# deliberately deferred until a domain and working HTTPS actually exist:
# enabling either before then breaks plain-HTTP testing/CI for no benefit.
SILENCED_SYSTEM_CHECKS = ['security.W004', 'security.W008']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'phonenumber_field',
    'organisations',
    'vendors',
    'events',
    'orders'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# DB-backed rather than the default per-process cache so counters (e.g. the
# rate limiter in orders/views.py) stay correct across multiple gunicorn
# workers, with no extra infrastructure (Redis etc.) required. The table is
# created by organisations/migrations/0004_create_cache_table.py.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache_table',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Dublin'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# The manifest storage requires collectstatic to have already run (it errors
# on any {% static %} reference missing from the manifest), so it's only used
# once DEBUG is off. Dev/test keep Django's plain static storage, unchanged.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"
                    if not DEBUG else "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# User-uploaded media (e.g. Organisation.image). Served in dev via
# config/urls.py; production serving is a separate, host-dependent decision
# (whitenoise above only handles collectstatic'd static assets, not runtime
# uploads) left for whenever the actual hosting choice is made.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# phonenumber_field settings
PHONENUMBER_DEFAULT_REGION = 'IE'

# Auth
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'organisations:my_organisations'
LOGOUT_REDIRECT_URL = 'login'

# Email: console backend by default so password-reset emails are visible
# during local dev with zero setup. Point EMAIL_BACKEND/EMAIL_HOST/etc at a
# real SMTP provider via env vars once one is chosen for the eventual host.
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@pizzapool.local')

# Plain stdout logging: works under docker logs, systemd/journald, or any
# PaaS log stream without further config.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'root': {'handlers': ['console'], 'level': 'INFO'},
}
