# Generated by Django 6.0.7 on 2026-07-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='shares_per_unit',
            new_name='portions_per_unit',
        ),
    ]
