# Generated by Django 6.0.7 on 2026-09-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_rename_shares_per_unit_menuitem_portions_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='portion_label',
            field=models.CharField(blank=True, help_text="e.g. 'slice' for pizza. Defaults to 'portion'.", max_length=30),
        ),
    ]
