# Generated by Django 6.0.7 on 2026-09-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_menuitem_portion_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='portion_label',
            field=models.CharField(blank=True, help_text="E.g. rename 'portion' to 'slice' for a pizza. Leave blank to keep 'portion'.", max_length=30),
        ),
    ]
