# Generated by Django 6.0.7 on 2026-08-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('USD', 'US Dollar ($)')], default='EUR', max_length=3),
        ),
    ]
