# Generated by Django 6.0.7 on 2026-08-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0004_create_cache_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='organisation_images/'),
        ),
    ]
