# Generated by Django 6.0.7 on 2026-07-22 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('vendors', '0002_rename_shares_per_unit_menuitem_portions_per_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='events.event')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='vendors.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='Portion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portion_number', models.PositiveIntegerField()),
                ('claimant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portions', to='orders.order')),
            ],
            options={
                'ordering': ['portion_number'],
                'unique_together': {('order', 'portion_number')},
            },
        ),
    ]
