# Generated by Django 6.0.7 on 2026-08-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='revolut_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
