# Generated by Django 6.0.7 on 2026-08-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_revolut_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='revolut_username',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
