# Generated by Django 6.0.7 on 2026-09-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_revolut_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='started_by_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='portion',
            name='is_starter_claim',
            field=models.BooleanField(default=False),
        ),
    ]
